#!/bin/sh /etc/rc.common

START=98

start () {
	echo "Waiting for bridge to start"
	sleep 10  # make sure bridge is up
	echo "Checking bridge mode or not"
	
	if [ `ifconfig | grep -m 1 br-lan | cut -d \  -f 1` ] 

	then
	
	echo "Device is in bridging mode."
	ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
	
	else 
	
	echo "Device is not in bridging mode."
	ifconfig eth0:9 172.31.255.254 netmask 255.255.255.252
	
	fi
}