#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }

	include /lib/network
	setup_switch

	sleep 5

	/sbin/wifi down
	/sbin/wifi up
	fallbackip
}

fallbackip(){
	FALLBACK=$(uci get secn.dhcp.FallbackIP)
	echo "$FALLBACK" > /var/run/test1
	if [ "$FALLBACK" == "enable" ]
	then
		echo "enable" > /var/run/test1
		echo "Adding FallBack IP"
		echo "Checking bridge mode or not"
	
		if [ `ifconfig | grep -m 1 br-lan | cut -d \  -f 1` ] 

		then
	
		echo "Device is in bridging mode."
		ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
	
		else 
	
		echo "Device is not in bridging mode."
		ifconfig eth0:9 172.31.255.254 netmask 255.255.255.252
	
		fi
	fi
}

restart() {
	ifdown -a
	sleep 1
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	service_stop /sbin/netifd
}

reload() {
	echo "Waiting for bridge to start"
	ubus call network reload
	/sbin/wifi down
	/sbin/wifi up
	fallbackip
}
